baseurl = "/"
title = "On Guessing Well"
author = "W.C. Telson"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "On Guessing Well"
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/davidwcnelson"
    weight = 3
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/davidwcnelson"
    weight = 4
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/davidwcnelson"
    weight = 5
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 6
