---
title: Chinese Resaurants and Indian Buffets
author: David W.C. Telson
date: '2019-07-15'
slug: chinese-restaurants-and-indian-buffets
categories: []
tags: []
draft: TRUE
---

Today I wanted to talk about one of my all time favorite subjects in probability theory: stochastic processes. Many stochastic processes can be thought of as sequences of random variables. For instance a Bernoulli process is a sequence of binary random variables, which can be though of as a listing of the outcomes of successive coin flips. Today we are going to talk about an interesting set of stochastic processes that are closely related to one of the most fundamental idea in probability and statistics: sampling.

# Sampling with Replacement

Our exploration begins with arguably the simplest of sampling methods: sampling with replacement. In this scheme, we make a random selection of an element from a set of possible outcomes (often we use the metaphor of a bag of different colored marbles), note what our selection was, and replace the element back into the set. 

# Sampling without Replacement

# Polya's Urn Model

# Chinese Restaurant Process

# Indian Buffet Process

