---
title: Making Our Best Guess
author: W.C. Telson
date: '2019-02-03T14:32:00'
categories:
tags:
  - probabilityTheory
  - decisionTheory
  - predictiveInference
  - machineLearning
  - statistics
  - dataScience
draft: yes
slug: making-our-best-guess
---

This post is an attempt to express the general theme of this blog: "how can we make good decisions under uncertainty?", or as I prefer "how can we guess well?" As a data scientist my role is to support decision makers by recommending a course of action that is likely to achieve their goals. This task requires us to predict (or guess) at how likely any set of actions is to succeed. In order to do this, we need to explore issues of ranging from the highly technical to the highly philosophical. 

Here is a brief overview of some of the posts that we will see in the near future:

- The Decision Support Framework
- Measures of Central Tendancy
- Interpretations of Probability
- Basic Probability Theory
- Bayes Theorem
- Expectation and Variance
- Information Theory and Entropy





